package com.abc.monitor_server.mybatis.mapper;

import com.abc.monitor_server.mybatis.pojo.DBTestBean;

public interface DBTestBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_col10
     *
     * @mbg.generated
     */
    int insert(DBTestBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_col10
     *
     * @mbg.generated
     */
    int insertSelective(DBTestBean record);
}