package com.abc.monitor_server.mybatis.pojo;

public class DBTestBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innodb_col10.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innodb_col10.idx
     *
     * @mbg.generated
     */
    private Long idx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innodb_col10.int_1
     *
     * @mbg.generated
     */
    private Integer int1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innodb_col10.int_2
     *
     * @mbg.generated
     */
    private Integer int2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innodb_col10.bigint_1
     *
     * @mbg.generated
     */
    private Long bigint1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innodb_col10.bigint_2
     *
     * @mbg.generated
     */
    private Long bigint2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innodb_col10.bigint_3
     *
     * @mbg.generated
     */
    private Long bigint3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innodb_col10.varchar_1
     *
     * @mbg.generated
     */
    private String varchar1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innodb_col10.varchar_2
     *
     * @mbg.generated
     */
    private String varchar2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innodb_col10.varchar_3
     *
     * @mbg.generated
     */
    private String varchar3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innodb_col10.varchar_4
     *
     * @mbg.generated
     */
    private String varchar4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innodb_col10.text_1
     *
     * @mbg.generated
     */
    private String text1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innodb_col10.id
     *
     * @return the value of innodb_col10.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innodb_col10.id
     *
     * @param id the value for innodb_col10.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innodb_col10.idx
     *
     * @return the value of innodb_col10.idx
     *
     * @mbg.generated
     */
    public Long getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innodb_col10.idx
     *
     * @param idx the value for innodb_col10.idx
     *
     * @mbg.generated
     */
    public void setIdx(Long idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innodb_col10.int_1
     *
     * @return the value of innodb_col10.int_1
     *
     * @mbg.generated
     */
    public Integer getInt1() {
        return int1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innodb_col10.int_1
     *
     * @param int1 the value for innodb_col10.int_1
     *
     * @mbg.generated
     */
    public void setInt1(Integer int1) {
        this.int1 = int1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innodb_col10.int_2
     *
     * @return the value of innodb_col10.int_2
     *
     * @mbg.generated
     */
    public Integer getInt2() {
        return int2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innodb_col10.int_2
     *
     * @param int2 the value for innodb_col10.int_2
     *
     * @mbg.generated
     */
    public void setInt2(Integer int2) {
        this.int2 = int2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innodb_col10.bigint_1
     *
     * @return the value of innodb_col10.bigint_1
     *
     * @mbg.generated
     */
    public Long getBigint1() {
        return bigint1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innodb_col10.bigint_1
     *
     * @param bigint1 the value for innodb_col10.bigint_1
     *
     * @mbg.generated
     */
    public void setBigint1(Long bigint1) {
        this.bigint1 = bigint1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innodb_col10.bigint_2
     *
     * @return the value of innodb_col10.bigint_2
     *
     * @mbg.generated
     */
    public Long getBigint2() {
        return bigint2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innodb_col10.bigint_2
     *
     * @param bigint2 the value for innodb_col10.bigint_2
     *
     * @mbg.generated
     */
    public void setBigint2(Long bigint2) {
        this.bigint2 = bigint2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innodb_col10.bigint_3
     *
     * @return the value of innodb_col10.bigint_3
     *
     * @mbg.generated
     */
    public Long getBigint3() {
        return bigint3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innodb_col10.bigint_3
     *
     * @param bigint3 the value for innodb_col10.bigint_3
     *
     * @mbg.generated
     */
    public void setBigint3(Long bigint3) {
        this.bigint3 = bigint3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innodb_col10.varchar_1
     *
     * @return the value of innodb_col10.varchar_1
     *
     * @mbg.generated
     */
    public String getVarchar1() {
        return varchar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innodb_col10.varchar_1
     *
     * @param varchar1 the value for innodb_col10.varchar_1
     *
     * @mbg.generated
     */
    public void setVarchar1(String varchar1) {
        this.varchar1 = varchar1 == null ? null : varchar1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innodb_col10.varchar_2
     *
     * @return the value of innodb_col10.varchar_2
     *
     * @mbg.generated
     */
    public String getVarchar2() {
        return varchar2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innodb_col10.varchar_2
     *
     * @param varchar2 the value for innodb_col10.varchar_2
     *
     * @mbg.generated
     */
    public void setVarchar2(String varchar2) {
        this.varchar2 = varchar2 == null ? null : varchar2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innodb_col10.varchar_3
     *
     * @return the value of innodb_col10.varchar_3
     *
     * @mbg.generated
     */
    public String getVarchar3() {
        return varchar3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innodb_col10.varchar_3
     *
     * @param varchar3 the value for innodb_col10.varchar_3
     *
     * @mbg.generated
     */
    public void setVarchar3(String varchar3) {
        this.varchar3 = varchar3 == null ? null : varchar3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innodb_col10.varchar_4
     *
     * @return the value of innodb_col10.varchar_4
     *
     * @mbg.generated
     */
    public String getVarchar4() {
        return varchar4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innodb_col10.varchar_4
     *
     * @param varchar4 the value for innodb_col10.varchar_4
     *
     * @mbg.generated
     */
    public void setVarchar4(String varchar4) {
        this.varchar4 = varchar4 == null ? null : varchar4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innodb_col10.text_1
     *
     * @return the value of innodb_col10.text_1
     *
     * @mbg.generated
     */
    public String getText1() {
        return text1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innodb_col10.text_1
     *
     * @param text1 the value for innodb_col10.text_1
     *
     * @mbg.generated
     */
    public void setText1(String text1) {
        this.text1 = text1 == null ? null : text1.trim();
    }
}